version: '2'
services:
  rtorrent:
    image: rutorrent-flood
    container_name: rutorrent-flood
    restart: unless-stopped
    ports:
      - '8080:80'
      - '3000:3000'
      - '5000:5000'
      - '50000:50000'
      - '6881:6881/udp'
    volumes:
      - /opt/config/flood:/config
      - /opt/downloads:/downloads
    environment:
      PUID: 1000
      PGID:  10
      TZ: America/Denver
